name: "Go build"
description: "Build Go binary with custom environment"
inputs:
  output-path:
    description: "output binary path"
    required: true
    default: "main"
runs:
  using: 'docker'
  image: './dockerfiles/Dockerfile'
  entrypoint: './scripts/build.sh'
  args:
    - './'
    - ${{ inputs.output-path }}
