name: "Go build"
description: "Build Go binary with custom environment"
inputs:
  output-path:
    description: "output binary path"
    required: true
    default: "main"
  workspace:
    description: "workspace root path"
    required: true
    default: "../../../"
runs:
  using: 'docker'
  image: ${{ inputs.workspace }}/dockerfiles/Dockerfile
  entrypoint: scripts/build.sh
  args:
    - './'
    - ${{ inputs.output-path }}
