name: "Go build"
description: "Build Go binary with custom environment"
inputs:
  output-path:
    description: "output binary path"
    required: true
    default: "main"
  build-target:
    description: "Go build target path"
    required: true
    default: "./"
  build-platform:
    description: "Target build platform, linux, macos or windows"
    required: true
    default: linux
runs:
  using: 'docker'
  image: ../../../dockerfiles/Dockerfile
  entrypoint: scripts/gh-action-entrypoint.sh
  args:
    - scripts/build.sh # this is main script.
    - ${{ inputs.build-target }}
    - ${{ inputs.output-path }}
    - ${{ inputs.build-platform }}
