# This is a build workflow.
name: Custom-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Runs Custom build action in this repository.
      - name: Run Custom build action
        uses: './.github/actions/custom-build/'
        with:
          build-target: ./cmd/
          output-path: ${{ GITHUB_WORKSPACE }}/main

      # Runs a set of commands using the runners
      - name: Run built binary to confirm it works
        run: ${{ GITHUB_WORKSPACE }}/main a b c d e f g
